import { createStitches, PropertyValue, ScaleValue } from "@stitches/react";
import {
  amber,
  amberDark,
  mauve,
  mauveDark,
  tomato,
  tomatoDark,
  violet,
  violetDark,
  indigo,
  indigoDark,
  teal,
  tealDark,
  violetA,
  violetDarkA,
  indigoA,
  tomatoA,
  plum,
} from "@radix-ui/colors";

export const {
  createTheme,
  getCssText,
  globalCss,
  styled,
  reset,
  keyframes,
  css,
  config,
} = createStitches({
  theme: {
    colors: {
      ...plum,
      ...mauve,
      ...violet,
      ...amber,
      ...tomato,
      ...indigo,
      ...teal,
      ...violetA,
      ...indigoA,
      ...tomatoA,

      bodyBackground: "$gray2",
      bodyColor: "$gray12",

      brand1: "$violet1",
      brand2: "$violet2",
      brand3: "$violet3",
      brand4: "$violet4",
      brand5: "$violet5",
      brand6: "$violet6",
      brand7: "$violet7",
      brand8: "$violet8",
      brand9: "$violet9",
      brand10: "$violet10",
      brand11: "$violet11",
      brand12: "$violet12",

      brandA1: "$violetA1",
      brandA2: "$violetA2",
      brandA3: "$violetA3",
      brandA4: "$violetA4",
      brandA5: "$violetA5",
      brandA6: "$violetA6",
      brandA7: "$violetA7",
      brandA8: "$violetA8",
      brandA9: "$violetA9",
      brandA10: "$violetA10",
      brandA11: "$violetA11",
      brandA12: "$violetA12",

      secondary1: "$plum1",
      secondary2: "$plum2",
      secondary3: "$plum3",
      secondary4: "$plum4",
      secondary5: "$plum5",
      secondary6: "$plum6",
      secondary7: "$plum7",
      secondary8: "$plum8",
      secondary9: "$plum9",
      secondary10: "$plum10",
      secondary11: "$plum11",
      secondary12: "$plum12",

      // success
      success1: "$teal1",
      success2: "$teal2",
      success3: "$teal3",
      success4: "$teal4",
      success5: "$teal5",
      success6: "$teal6",
      success7: "$teal7",
      success8: "$teal8",
      success9: "$teal9",
      success10: "$teal10",
      success11: "$teal11",
      success12: "$teal12",

      // info
      info1: "$indigo1",
      info2: "$indigo2",
      info3: "$indigo3",
      info4: "$indigo4",
      info5: "$indigo5",
      info6: "$indigo6",
      info7: "$indigo7",
      info8: "$indigo8",
      info9: "$indigo9",
      info10: "$indigo10",
      info11: "$indigo11",
      info12: "$indigo12",

      // warning
      warning1: "$amber1",
      warning2: "$amber2",
      warning3: "$amber3",
      warning4: "$amber4",
      warning5: "$amber5",
      warning6: "$amber6",
      warning7: "$amber7",
      warning8: "$amber8",
      warning9: "$amber9",
      warning10: "$amber10",
      warning11: "$amber11",
      warning12: "$amber12",

      // danger
      danger1: "$tomato1",
      danger2: "$tomato2",
      danger3: "$tomato3",
      danger4: "$tomato4",
      danger5: "$tomato5",
      danger6: "$tomato6",
      danger7: "$tomato7",
      danger8: "$tomato8",
      danger9: "$tomato9",
      danger10: "$tomato10",
      danger11: "$tomato11",
      danger12: "$tomato12",

      // gray scale
      gray1: "$mauve1",
      gray2: "$mauve2",
      gray3: "$mauve3",
      gray4: "$mauve4",
      gray5: "$mauve5",
      gray6: "$mauve6",
      gray7: "$mauve7",
      gray8: "$mauve8",
      gray9: "$mauve9",
      gray10: "$mauve10",
      gray11: "$mauve11",
      gray12: "$mauve12",
    },

    space: {
      px: "1px",
      "0-5": "0.125rem",
      "1": "0.25rem",
      "1-5": "0.375rem",
      "2": "0.5rem",
      "2-5": "0.625rem",
      "3": "0.75rem",
      "3-5": "0.875rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "7": "1.75rem",
      "8": "2rem",
      "9": "2.25rem",
      "10": "2.5rem",
      "11": "2.75rem",
      "12": "3rem",
      "14": "3.5rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "28": "7rem",
      "32": "8rem",
      "36": "9rem",
      "40": "10rem",
      "44": "11rem",
      "48": "12rem",
      "52": "13rem",
      "56": "14rem",
      "60": "15rem",
      "64": "16rem",
      "72": "18rem",
      "80": "20rem",
      "96": "24rem",
    },
    fonts: {
      sans: "DM Sans; sans-serif;",
    },
    fontSizes: {
      xs: "0.75rem",
      sm: ".875rem",
      base: "1rem",
      md: "1.0625rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    shadows: {},
    transitions: {},
    radii: {
      basic: "0.25rem",
      sm: "0.125rem",
      md: "0.375rem",
      lg: "0.50rem",
      xl: "0.75rem",
      "2xl": "1rem",
      "3xl": "1.5rem",
      full: "9999px",
    },
  },
  utils: {
    bg: (value: PropertyValue<"backgroundColor">) => ({
      backgroundColor: value,
    }),
    size: (value: ScaleValue<"sizes">) => ({
      width: value,
      height: value,
    }),
    p: (value: PropertyValue<"padding">) => ({
      padding: value,
    }),
    px: (value: PropertyValue<"padding">) => ({
      paddingRight: value,
      paddingLeft: value,
    }),
    py: (value: PropertyValue<"padding">) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
    pr: (value: PropertyValue<"paddingRight">) => ({
      paddingRight: value,
    }),
    pl: (value: PropertyValue<"paddingLeft">) => ({
      paddingLeft: value,
    }),
    pt: (value: PropertyValue<"paddingTop">) => ({
      paddingTop: value,
    }),
    pb: (value: PropertyValue<"paddingBottom">) => ({
      paddingBottom: value,
    }),
    m: (value: PropertyValue<"margin">) => ({
      margin: value,
    }),
    mx: (value: PropertyValue<"margin">) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: PropertyValue<"margin">) => ({
      marginTop: value,
      marginBottom: value,
    }),
    mr: (value: PropertyValue<"marginRight">) => ({
      marginRight: value,
    }),
    ml: (value: PropertyValue<"marginLeft">) => ({
      marginLeft: value,
    }),
    mt: (value: PropertyValue<"marginTop">) => ({
      marginTop: value,
    }),
    mb: (value: PropertyValue<"marginBottom">) => ({
      marginBottom: value,
    }),
    br: (value: PropertyValue<"borderRadius">) => ({
      borderRadius: value,
    }),
  },
  media: {
    sm: "(min-width: 640px)",
    md: "(min-width: 768px)",
    lg: "(min-width: 1024px)",
  },
});

export const darkTheme = createTheme("dark-theme", {
  colors: {
    ...mauveDark,
    ...violetDark,
    ...amberDark,
    ...tomatoDark,
    ...indigoDark,
    ...tealDark,
    ...violetDarkA,

    bodyBackground: "$gray2",
    bodyColor: "#fff",
  },
});

export type { CSS, VariantProps } from "@stitches/react";
